name: D3F4ULT-XMD-2
services:
  - name: D3F4ULT-XMD-2
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin



      
